"""Initial migration

Revision ID: 672b8fbf29a7
Revises: 
Create Date: 2026-03-01 19:14:53.427263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '672b8fbf29a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_answers_question_id'))
        batch_op.drop_index(batch_op.f('idx_answers_response_id'))
        batch_op.drop_constraint(batch_op.f('answers_question_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('answers_option_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('answers_response_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'options', ['option_id'], ['id'])
        batch_op.create_foreign_key(None, 'responses', ['response_id'], ['id'])
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_options_question_id'))
        batch_op.drop_constraint(batch_op.f('options_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_questions_order'))
        batch_op.drop_index(batch_op.f('idx_questions_survey_id'))
        batch_op.drop_constraint(batch_op.f('questions_survey_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'surveys', ['survey_id'], ['id'])
        batch_op.drop_column('order_index')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_responses_survey_id'))
        batch_op.drop_index(batch_op.f('idx_responses_user_id'))
        batch_op.drop_constraint(batch_op.f('responses_survey_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('responses_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'surveys', ['survey_id'], ['id'])

    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='survey_status'),
               nullable=False,
               existing_server_default=sa.text("'draft'::survey_status"))
        batch_op.drop_index(batch_op.f('idx_surveys_author_id'))
        batch_op.drop_index(batch_op.f('idx_surveys_status'))
        batch_op.drop_constraint(batch_op.f('surveys_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('surveys_author_id_fkey'), 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_surveys_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_surveys_author_id'), ['author_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='survey_status'),
               nullable=True,
               existing_server_default=sa.text("'draft'::survey_status"))

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('responses_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('responses_survey_id_fkey'), 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_responses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_responses_survey_id'), ['survey_id'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questions_survey_id_fkey'), 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_questions_survey_id'), ['survey_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_questions_order'), ['survey_id', 'order_index'], unique=False)
        batch_op.drop_column('order')

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('options_question_id_fkey'), 'questions', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_options_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answers_response_id_fkey'), 'responses', ['response_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('answers_option_id_fkey'), 'options', ['option_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('answers_question_id_fkey'), 'questions', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_answers_response_id'), ['response_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###
